Add missing keyboard symbols
rsubtil/controller_icons pull request #107
Opened 2024-09-05 15:34 UTC by TacticalLaptopBag

Fixes #106

Adds additional missing keyboard symbols and maps `QuoteLeft` to the icon for `tilde` as the tilde key `~` is more recognizable than backtick (`), and the mapping was missing despite the icon being present.

Symbols added:
- Apostrophe `'`
- Comma `,`
- Period `.`
- Equals `=`
- Forward slash `/`

Each of the icons were created by modifying other existing icons, so the overall style is retained.

2024-09-05 15:52 UTC, TacticalLaptopBag commented
Possible problem: For some reason, on my laptop, assigning an action to `,` will make controller icons look for `KEY_KP_PERIOD`, despite it being a comma and not a period. This could be a weird Dvorak problem though, I will continue to investigate

2024-09-05 16:06 UTC, TacticalLaptopBag commented
![image](https://github.com/user-attachments/assets/a045bc06-8b33-4c7d-a919-7687120f89d3)

I understand the root of the problem now. In `_convert_event_to_path` it checks if the keycode is 0. If it is, it gets the keycode from the DisplayServer using the physical keycode. For whatever reason, the DisplayServer believes that `,` comma is actually KEY_KP_PERIOD. I need to test whether this is just my laptop, Dvorak doing weird things, or if this is actually a problem.

2024-09-05 16:12 UTC, TacticalLaptopBag commented
This is a Dvorak issue. I have added `KEY_KP_PERIOD` to the key match since that should map to period anyway. This problem isn't an issue with Controller Icons, so this PR is ready once again

2024-09-08 09:44 UTC, rsubtil requested changes
Thank you for your contribution, and for creating new icons not available in the original pack! There are two small issues that need to be agdressed, but other than that I'm happy to merge this.

Additionally, the new icons you created are derivative works, and thus are not automatically licensed with the same original license (CC0). I can only accept these if you choose to license them with the same license ([description of CC0](https://creativecommons.org/publicdomain/zero/1.0/)). Please confirm if you agree with this. I will still credit you for the creation of these assets on the main README file of this repository.

2024-09-08 09:44 UTC, rsubtil commented on addons/controller_icons/ControllerIcons.gd
> +			return "key/forwardslash"
For consistency with other asset names, please add an underscore to separate these words (rename the icon as well):
```suggestion
			return "key/forward_slash"
```

2024-09-08 09:44 UTC, rsubtil commented on addons/controller_icons/ControllerIcons.gd
> +		KEY_ASCIITILDE, KEY_QUOTELEFT:
`KEY_QUOTELEFT` should be mapped to a dedicated \` character instead. Could you create an icon specific to it as well?

2024-09-08 11:45 UTC, TacticalLaptopBag commented
I agree to using the license - I'll get to work on the changes as soon as I can

2024-09-08 13:15 UTC, TacticalLaptopBag commented
Created an icon for `KEY_QUOTELEFT` and renamed forwardslash -> forward_slash

2024-09-09 09:34 UTC, rsubtil approved these changes

2024-09-09 09:35 UTC, merged

2024-09-09 09:35 UTC, rsubtil commented
Thank you so much for your contribution!