Added the option to change the icon file extension from png to other …
rsubtil/controller_icons pull request #88
Opened 2024-05-06 12:12 UTC by plyoung

…like tres or svg

2024-05-07 18:33 UTC, rsubtil requested changes
Thank you for your contribution! There's only a minor point that I'd like to change regarding how this works.

All custom properties work in the basis of having no data whatsoever if the user doesn't specify it explicitly. So in general, the code tests if these custom properties have any content, and it not, fallback to a default value, such as in `custom_label_settings`, `custom_mapper` and `custom_asset_dir`:

https://github.com/rsubtil/controller_icons/blob/bd58e50c8b39dafd8f23f0a82da2c380ea713c49/addons/controller_icons/objects/ControllerIconTexture.gd#L135-L139
https://github.com/rsubtil/controller_icons/blob/bd58e50c8b39dafd8f23f0a82da2c380ea713c49/addons/controller_icons/ControllerIcons.gd#L102-L107
https://github.com/rsubtil/controller_icons/blob/bd58e50c8b39dafd8f23f0a82da2c380ea713c49/addons/controller_icons/ControllerIcons.gd#L197-L202

So in that vein, could you change the `file_extension` to follow this same pattern? Essentially, have the default `png` extension and code, and changing it if this settings is not empty:

```gdscript
# In ControllerIcons.gd
var base_extension := "png"

...
func _ready():
    ...
    if _settings.custom_file_extension:
        base_extension = _settings.custom_file_extension
    ...
```

2024-05-07 18:33 UTC, rsubtil commented on addons/controller_icons/Settings.gd
> +@export var file_extension : String = "png"
Could you also rename this to `custom_file_extension` to further denote this?
```suggestion
@export var custom_file_extension : String = "png"
```

2024-05-08 08:44 UTC, plyoung commented
I've made the changes. Hope it is right. I've not worked with pull requests before.

2024-05-08 17:00 UTC, rsubtil commented
> I've made the changes. Hope it is right. I've not worked with pull requests before.

It's alright! There were some minor issues left, but I went ahead and added a commit to tackle them:

- Renamed to `_base_extension` since it is a private variable
- Move `var _base_extension` elsewhere to be more inline with other variables
- Regenerate `settings.tres` as it was still using the old `file_extension` name

2024-05-08 17:01 UTC, rsubtil approved these changes

2024-05-08 17:01 UTC, merged

2024-05-08 17:02 UTC, rsubtil commented
Thank you so much for your contribution! :tada: